name: Build & Release
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\python -m pip install --upgrade pip
          .\.venv\Scripts\python -m pip install -r requirements.txt
          .\.venv\Scripts\python -m pip install pyinstaller
          
      - name: Build exe
        run: |
          .\.venv\Scripts\python -m PyInstaller --onefile --windowed --icon assets/icon.ico --name HWPViewer --distpath dist --workpath build main.py
          
      - name: Check Build Result
        shell: pwsh
        run: |
          if (Test-Path "dist/HWPViewer.exe") {
            Write-Host "Build Successful: dist/HWPViewer.exe exists."
          } else {
            Write-Error "Build Failed: dist/HWPViewer.exe not found."
            exit 1
          }
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/HWPViewer.exe
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/HWPViewer.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
